/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class StateMachineGrammarAccess extends AbstractGrammarElementFinder {
	
	public class StateMachineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.StateMachine.StateMachine");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEventKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cBlockKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cEventAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cEventEventParserRuleCall_5_0 = (RuleCall)cEventAssignment_5.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cStopKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cResetKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cBlockKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cLeftParenthesisKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cEventResetAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final CrossReference cEventResetEventCrossReference_11_0 = (CrossReference)cEventResetAssignment_11.eContents().get(0);
		private final RuleCall cEventResetEventIDTerminalRuleCall_11_0_1 = (RuleCall)cEventResetEventCrossReference_11_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cStopKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cInstructionsKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cBlockKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Keyword cLeftParenthesisKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Assignment cInstructionsAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final RuleCall cInstructionsInstructionParserRuleCall_17_0 = (RuleCall)cInstructionsAssignment_17.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_18 = (Keyword)cGroup.eContents().get(18);
		private final Keyword cStopKeyword_19 = (Keyword)cGroup.eContents().get(19);
		private final Assignment cStateAssignment_20 = (Assignment)cGroup.eContents().get(20);
		private final RuleCall cStateStateParserRuleCall_20_0 = (RuleCall)cStateAssignment_20.eContents().get(0);
		
		//StateMachine:
		//	("Name" name+=STRING
		//	"Event" "block" "(" event+=Event* ")" "stop"
		//	"Reset" "block" "(" eventReset+=[Event]* ")" "stop"
		//	"Instructions" "block" "(" instructions+=Instruction* ")" "stop"
		//	state+=State*)*;
		@Override public ParserRule getRule() { return rule; }
		
		//("Name" name+=STRING "Event" "block" "(" event+=Event* ")" "stop" "Reset" "block" "(" eventReset+=[Event]* ")" "stop"
		//"Instructions" "block" "(" instructions+=Instruction* ")" "stop" state+=State*)*
		public Group getGroup() { return cGroup; }
		
		//"Name"
		public Keyword getNameKeyword_0() { return cNameKeyword_0; }
		
		//name+=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
		
		//"Event"
		public Keyword getEventKeyword_2() { return cEventKeyword_2; }
		
		//"block"
		public Keyword getBlockKeyword_3() { return cBlockKeyword_3; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_4() { return cLeftParenthesisKeyword_4; }
		
		//event+=Event*
		public Assignment getEventAssignment_5() { return cEventAssignment_5; }
		
		//Event
		public RuleCall getEventEventParserRuleCall_5_0() { return cEventEventParserRuleCall_5_0; }
		
		//")"
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
		
		//"stop"
		public Keyword getStopKeyword_7() { return cStopKeyword_7; }
		
		//"Reset"
		public Keyword getResetKeyword_8() { return cResetKeyword_8; }
		
		//"block"
		public Keyword getBlockKeyword_9() { return cBlockKeyword_9; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_10() { return cLeftParenthesisKeyword_10; }
		
		//eventReset+=[Event]*
		public Assignment getEventResetAssignment_11() { return cEventResetAssignment_11; }
		
		//[Event]
		public CrossReference getEventResetEventCrossReference_11_0() { return cEventResetEventCrossReference_11_0; }
		
		//ID
		public RuleCall getEventResetEventIDTerminalRuleCall_11_0_1() { return cEventResetEventIDTerminalRuleCall_11_0_1; }
		
		//")"
		public Keyword getRightParenthesisKeyword_12() { return cRightParenthesisKeyword_12; }
		
		//"stop"
		public Keyword getStopKeyword_13() { return cStopKeyword_13; }
		
		//"Instructions"
		public Keyword getInstructionsKeyword_14() { return cInstructionsKeyword_14; }
		
		//"block"
		public Keyword getBlockKeyword_15() { return cBlockKeyword_15; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_16() { return cLeftParenthesisKeyword_16; }
		
		//instructions+=Instruction*
		public Assignment getInstructionsAssignment_17() { return cInstructionsAssignment_17; }
		
		//Instruction
		public RuleCall getInstructionsInstructionParserRuleCall_17_0() { return cInstructionsInstructionParserRuleCall_17_0; }
		
		//")"
		public Keyword getRightParenthesisKeyword_18() { return cRightParenthesisKeyword_18; }
		
		//"stop"
		public Keyword getStopKeyword_19() { return cStopKeyword_19; }
		
		//state+=State*
		public Assignment getStateAssignment_20() { return cStateAssignment_20; }
		
		//State
		public RuleCall getStateStateParserRuleCall_20_0() { return cStateStateParserRuleCall_20_0; }
	}
	public class InstructionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.StateMachine.Instruction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValueIDTerminalRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		
		//Instruction:
		//	name=ID value=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID value=ID
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//value=ID
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }
		
		//ID
		public RuleCall getValueIDTerminalRuleCall_1_0() { return cValueIDTerminalRuleCall_1_0; }
	}
	public class EventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.StateMachine.Event");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValueIDTerminalRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		
		//Event:
		//	name=ID value=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID value=ID
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//value=ID
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }
		
		//ID
		public RuleCall getValueIDTerminalRuleCall_1_0() { return cValueIDTerminalRuleCall_1_0; }
	}
	public class StateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.StateMachine.State");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cBlockKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cActionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cActionsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cActionsInstructionCrossReference_4_1_0 = (CrossReference)cActionsAssignment_4_1.eContents().get(0);
		private final RuleCall cActionsInstructionIDTerminalRuleCall_4_1_0_1 = (RuleCall)cActionsInstructionCrossReference_4_1_0.eContents().get(1);
		private final Assignment cMovesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cMovesMoveParserRuleCall_5_0 = (RuleCall)cMovesAssignment_5.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cStopKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//State:
		//	"State" name=ID "block" "(" ("action" actions+=[Instruction]+)?
		//	moves+=Move* ")" "stop";
		@Override public ParserRule getRule() { return rule; }
		
		//"State" name=ID "block" "(" ("action" actions+=[Instruction]+)? moves+=Move* ")" "stop"
		public Group getGroup() { return cGroup; }
		
		//"State"
		public Keyword getStateKeyword_0() { return cStateKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//"block"
		public Keyword getBlockKeyword_2() { return cBlockKeyword_2; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }
		
		//("action" actions+=[Instruction]+)?
		public Group getGroup_4() { return cGroup_4; }
		
		//"action"
		public Keyword getActionKeyword_4_0() { return cActionKeyword_4_0; }
		
		//actions+=[Instruction]+
		public Assignment getActionsAssignment_4_1() { return cActionsAssignment_4_1; }
		
		//[Instruction]
		public CrossReference getActionsInstructionCrossReference_4_1_0() { return cActionsInstructionCrossReference_4_1_0; }
		
		//ID
		public RuleCall getActionsInstructionIDTerminalRuleCall_4_1_0_1() { return cActionsInstructionIDTerminalRuleCall_4_1_0_1; }
		
		//moves+=Move*
		public Assignment getMovesAssignment_5() { return cMovesAssignment_5; }
		
		//Move
		public RuleCall getMovesMoveParserRuleCall_5_0() { return cMovesMoveParserRuleCall_5_0; }
		
		//")"
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
		
		//"stop"
		public Keyword getStopKeyword_7() { return cStopKeyword_7; }
	}
	public class MoveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.StateMachine.Move");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cEventAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cEventEventCrossReference_0_0 = (CrossReference)cEventAssignment_0.eContents().get(0);
		private final RuleCall cEventEventIDTerminalRuleCall_0_0_1 = (RuleCall)cEventEventCrossReference_0_0.eContents().get(1);
		private final Keyword cToKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cStateAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cStateStateCrossReference_2_0 = (CrossReference)cStateAssignment_2.eContents().get(0);
		private final RuleCall cStateStateIDTerminalRuleCall_2_0_1 = (RuleCall)cStateStateCrossReference_2_0.eContents().get(1);
		
		//Move:
		//	event=[Event] "to" state=[State];
		@Override public ParserRule getRule() { return rule; }
		
		//event=[Event] "to" state=[State]
		public Group getGroup() { return cGroup; }
		
		//event=[Event]
		public Assignment getEventAssignment_0() { return cEventAssignment_0; }
		
		//[Event]
		public CrossReference getEventEventCrossReference_0_0() { return cEventEventCrossReference_0_0; }
		
		//ID
		public RuleCall getEventEventIDTerminalRuleCall_0_0_1() { return cEventEventIDTerminalRuleCall_0_0_1; }
		
		//"to"
		public Keyword getToKeyword_1() { return cToKeyword_1; }
		
		//state=[State]
		public Assignment getStateAssignment_2() { return cStateAssignment_2; }
		
		//[State]
		public CrossReference getStateStateCrossReference_2_0() { return cStateStateCrossReference_2_0; }
		
		//ID
		public RuleCall getStateStateIDTerminalRuleCall_2_0_1() { return cStateStateIDTerminalRuleCall_2_0_1; }
	}
	
	
	private final StateMachineElements pStateMachine;
	private final InstructionElements pInstruction;
	private final EventElements pEvent;
	private final StateElements pState;
	private final MoveElements pMove;
	private final TerminalRule tSTRING;
	private final TerminalRule tDOUBLE;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public StateMachineGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pStateMachine = new StateMachineElements();
		this.pInstruction = new InstructionElements();
		this.pEvent = new EventElements();
		this.pState = new StateElements();
		this.pMove = new MoveElements();
		this.tSTRING = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.StateMachine.STRING");
		this.tDOUBLE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.StateMachine.DOUBLE");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.StateMachine".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//StateMachine:
	//	("Name" name+=STRING
	//	"Event" "block" "(" event+=Event* ")" "stop"
	//	"Reset" "block" "(" eventReset+=[Event]* ")" "stop"
	//	"Instructions" "block" "(" instructions+=Instruction* ")" "stop"
	//	state+=State*)*;
	public StateMachineElements getStateMachineAccess() {
		return pStateMachine;
	}
	
	public ParserRule getStateMachineRule() {
		return getStateMachineAccess().getRule();
	}
	
	//Instruction:
	//	name=ID value=ID;
	public InstructionElements getInstructionAccess() {
		return pInstruction;
	}
	
	public ParserRule getInstructionRule() {
		return getInstructionAccess().getRule();
	}
	
	//Event:
	//	name=ID value=ID;
	public EventElements getEventAccess() {
		return pEvent;
	}
	
	public ParserRule getEventRule() {
		return getEventAccess().getRule();
	}
	
	//State:
	//	"State" name=ID "block" "(" ("action" actions+=[Instruction]+)?
	//	moves+=Move* ")" "stop";
	public StateElements getStateAccess() {
		return pState;
	}
	
	public ParserRule getStateRule() {
		return getStateAccess().getRule();
	}
	
	//Move:
	//	event=[Event] "to" state=[State];
	public MoveElements getMoveAccess() {
		return pMove;
	}
	
	public ParserRule getMoveRule() {
		return getMoveAccess().getRule();
	}
	
	//@Override
	//terminal STRING:
	//	'"' ('\\' ('b' | 't' | 'n' | 'f' | 'r' | 'u' | '"' | "'" | '\\') | !('\\' | '"'))* '"' |
	//	"'" ('\\' ('b' | 't' | 'n' | 'f' | 'r' | 'u' | '"' | "'" | '\\') | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return tSTRING;
	}
	
	//terminal DOUBLE:
	//	INT '.' INT;
	public TerminalRule getDOUBLERule() {
		return tDOUBLE;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
