/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.stateMachine;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.stateMachine.StateMachinePackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends Trigger
{
} // Expression
