/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.stateMachine;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.stateMachine.Gate#getBlock <em>Block</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.stateMachine.StateMachinePackage#getGate()
 * @model
 * @generated
 */
public interface Gate extends EObject
{
  /**
   * Returns the value of the '<em><b>Block</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.stateMachine.Block}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Block</em>' containment reference list.
   * @see org.xtext.example.mydsl.stateMachine.StateMachinePackage#getGate_Block()
   * @model containment="true"
   * @generated
   */
  EList<Block> getBlock();

} // Gate
