/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.statemachine.ui.internal.StatemachineActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class StateMachineExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(StatemachineActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		StatemachineActivator activator = StatemachineActivator.getInstance();
		return activator != null ? activator.getInjector(StatemachineActivator.ORG_XTEXT_EXAMPLE_MYDSL_STATEMACHINE) : null;
	}

}
