/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.serializer;

import org.xtext.example.mydsl.serializer.AbstractStateMachineSemanticSequencer;

@SuppressWarnings("all")
public class StateMachineSemanticSequencer extends AbstractStateMachineSemanticSequencer {
}
