/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.ui;

import hover.StateMachineHoverProvider;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.DefaultSemanticHighlightingCalculator;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.xtext.example.mydsl.ui.AbstractStateMachineUiModule;
import syntaxHighlighting.StateMachineHighlighting;
import syntaxHighlighting.StateMachineSemanticHighligther;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class StateMachineUiModule extends AbstractStateMachineUiModule {
  public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
    return StateMachineHighlighting.class;
  }
  
  public Class<? extends DefaultSemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
    return StateMachineSemanticHighligther.class;
  }
  
  public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
    return StateMachineHoverProvider.class;
  }
  
  public StateMachineUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
